### ISSUE TITLE
Duplicate data

### ISSUE THREAD

**Issue by datinho** [snowplow-archive/cloudfront-log-deserializer#5]
Hi,
I'm facing a problem with duplicated data. Under cloudera hadoop on premise I've created an Hive table with SERDE:

> CREATE_ EXTERNAL TABLE 'opslogs.img_musvc5_log'(
>   'dt' string COMMENT 'from deserializer', 
>   'tm' string COMMENT 'from deserializer', 
>   'edgelocation' string COMMENT 'from deserializer', 
>   'bytessent' int COMMENT 'from deserializer', 
>   'ipaddress' string COMMENT 'from deserializer', 
>   'operation' string COMMENT 'from deserializer', 
>   'domain' string COMMENT 'from deserializer', 
>   'object' string COMMENT 'from deserializer', 
>   'httpstatus' int COMMENT 'from deserializer', 
>   'referrer' string COMMENT 'from deserializer', 
>   'useragent' string COMMENT 'from deserializer', 
>   'querystring' string COMMENT 'from deserializer')
> ROW FORMAT SERDE 
>   'com.snowplowanalytics.hive.serde.CfLogDeserializer' 
> LOCATION
>   'hdfs://nameservice1/loader/opslogs/img-musvc5-log

and under its path the gzip from cloudfront:

> $ zgrep '0HPJdU3oosCQCDWLbCyiJJfeotm2fw' musvc5_20161012151922.gz 
> 2016-10-12  13:04:00    MRS50   2331    77.43.27.164    GET dpdbnhcc1iuoz.cloudfront.net    /static/54293/images/Modelli/logo_mailup.png    200 -   Mozilla/5.0%2520(iPad;%2520CPU%2520OS%25209_3_5%2520like%2520Mac%2520OS%2520X)%2520AppleWebKit/601.1.46%2520(KHTML,%2520like%2520Gecko)%2520Mobile/13G36    -   -   Hit woOLVwkwUg6Et1mfm35Wkf--0HPJdU3oosCQCDWLbCyiJJfeotm2fw==    img.musvc5.net  http    290 0.006   -   -   -   Hit HTTP/1.1

Note: the file is a concatenation of two or more cloudfront gzipped file.

But when I query the table under hive cli here's the result:

> hive> select \* from opslogs.img_musvc5_log where querystring like '%0HPJdU3oosCQCDWLbCyiJJfeotm2fw%';
> Query ID = loader_dwh_20161012154646_d7983885-6154-4f93-a665-a9feec3a023d
> .
> .
> Stage-Stage-1: Map: 1   Cumulative CPU: 11.54 sec   HDFS Read: 44373443 HDFS Write: 1188 SUCCESS
> Total MapReduce CPU Time Spent: 11 seconds 540 msec
> OK
> 2016-10-12  13:04:00    MRS50   2331    77.43.27.164    GET dpdbnhcc1iuoz.cloudfront.net    /static/54293/images/Modelli/logo_mailup.png    200 NULL    Mozilla/5.0%2520(iPad;%2520CPU%2520OS%25209_3_5%2520like%2520Mac%2520OS%2520X)%2520AppleWebKit/601.1.46%2520(KHTML,%2520like%2520Gecko)%2520Mobile/13G36    -   -   Hit woOLVwkwUg6Et1mfm35Wkf--0HPJdU3oosCQCDWLbCyiJJfeotm2fw==    img.musvc5.net  http    290 0.006   -   -   -   Hit HTTP/1.1
> 2016-10-12  13:04:00    MRS50   2331    77.43.27.164    GET dpdbnhcc1iuoz.cloudfront.net    /static/54293/images/Modelli/logo_mailup.png    200 NULL    Mozilla/5.0%2520(iPad;%2520CPU%2520OS%25209_3_5%2520like%2520Mac%2520OS%2520X)%2520AppleWebKit/601.1.46%2520(KHTML,%2520like%2520Gecko)%2520Mobile/13G36    -   -   Hit woOLVwkwUg6Et1mfm35Wkf--0HPJdU3oosCQCDWLbCyiJJfeotm2fw==    img.musvc5.net  http    290 0.006   -   -   -   Hit HTTP/1.1
> 2016-10-12  13:04:00    MRS50   2331    77.43.27.164    GET dpdbnhcc1iuoz.cloudfront.net    /static/54293/images/Modelli/logo_mailup.png    200 NULL    Mozilla/5.0%2520(iPad;%2520CPU%2520OS%25209_3_5%2520like%2520Mac%2520OS%2520X)%2520AppleWebKit/601.1.46%2520(KHTML,%2520like%2520Gecko)%2520Mobile/13G36    -   -   Hit woOLVwkwUg6Et1mfm35Wkf--0HPJdU3oosCQCDWLbCyiJJfeotm2fw==    img.musvc5.net  http    290 0.006   -   -   -   Hit HTTP/1.1
> Time taken: 30.772 seconds, Fetched: 3 row(s)

So I've found 3 duplicated rows from the only one present into file.
If needed I can provide the file of this issue (around 43 Mb).

**Comment by alexanderdean** [comment]
CloudFront logs can contain duplicates - you'll need to de-duplicate downstream of running the serde.

**Comment by datinho** [comment]
Thanks for reply.  I wrote the output of zgrep because the record provided from Cloudfront is single. 
Anyway I'll follow the reply deduplicating the SERDE output.
